---
services:
  ts-devcontainer:
    image: tailscale/tailscale:latest
    container_name: ts-devcontainer
    hostname: devcontainer
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  devcontainer:
    build: .
    container_name: devcontainer
    network_mode: service:ts-devcontainer
    depends_on:
      - ts-devcontainer
    volumes:
      - devcontainer-data:/app/data/
      - dev-home:/home/stefan
    environment:
      - TZ=Europe/Berlin
    #restart: unless-stopped
    restart: no

volumes:
  dev-home:
  ts-state:
  devcontainer-data:
    driver: local
  ts-devcontainer:
    driver: local
